import {getChatGPTUser} from '../../chatgpt-auth';
import {bindings,isBroker,modes,statuses,uid,now,text} from '@/lib/portal';
export const dynamic='force-dynamic';
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
class Denied extends Error{constructor(public status:number,message:string){super(message)}}
async function identity(){const u=await getChatGPTUser();if(!u)throw new Denied(401,'Sign in to access your private workspace.');return {...u,broker:isBroker(u.email)};}
async function own(id:string,u:Awaited<ReturnType<typeof identity>>){const r=await bindings().DB.prepare('SELECT * FROM requests WHERE id=?').bind(id).first<Record<string,unknown>>();if(!r||(!u.broker&&r.owner!==u.userId))throw new Denied(404,'Request not found.');return r;}
async function log(actor:string,action:string,target:string){return bindings().DB.prepare('INSERT INTO audit (id,actor,action,target,created) VALUES (?,?,?,?,?)').bind(uid(),actor,action,target,now()).run();}
function failure(e:unknown){if(e instanceof Denied)return json({error:e.message},e.status);console.error('Portal operation failed',e);return json({error:'We could not complete this action. Your input has been kept. Please try again.'},503);}
export async function GET(req:Request){try{const u=await identity(),{DB,BUCKET}=bindings(),url=new URL(req.url),section=url.searchParams.get('section')||'workspace';
if(section==='file'){const id=url.searchParams.get('id')||'';const f=await DB.prepare('SELECT * FROM files WHERE id=?').bind(id).first<{request:string;name:string;mime:string}>();if(!f)throw new Denied(404,'File not found.');await own(f.request,u);if(!BUCKET)throw new Denied(503,'Document storage unavailable.');const blob=await BUCKET.get(id);if(!blob)throw new Denied(404,'File not found.');return new Response(blob.body,{headers:{'Content-Type':f.mime,'Content-Disposition':`${url.searchParams.get('preview')==='1'&&['image/jpeg','image/png'].includes(f.mime)?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
if(section==='detail'){const id=url.searchParams.get('id')||'',r=await own(id,u);const [events,files,appointments]=await Promise.all([DB.prepare('SELECT * FROM events WHERE request=? AND (?=1 OR internal=0) ORDER BY created').bind(id,u.broker?1:0).all(),DB.prepare('SELECT * FROM files WHERE request=? ORDER BY created DESC').bind(id).all(),DB.prepare('SELECT * FROM appointments WHERE request=? ORDER BY date').bind(id).all()]);return json({request:r,events:events.results,files:files.results,appointments:appointments.results});}
if(section==='admin'){if(!u.broker)throw new Denied(403,'This workspace is restricted to authorised brokerage staff.');const [requests,appointments,tickets,matches,commissions,audit]=await Promise.all(['requests','appointments','tickets','matches','commissions','audit'].map(table=>DB.prepare(`SELECT * FROM ${table} LIMIT 1000`).all()));return json({requests:requests.results,appointments:appointments.results,tickets:tickets.results,matches:matches.results,commissions:commissions.results,audit:audit.results});}
const [requests,appointments,tickets,profile]=await Promise.all([DB.prepare('SELECT * FROM requests WHERE owner=? ORDER BY created DESC').bind(u.userId).all(),DB.prepare('SELECT * FROM appointments WHERE owner=? ORDER BY date DESC').bind(u.userId).all(),DB.prepare('SELECT * FROM tickets WHERE owner=? ORDER BY created DESC').bind(u.userId).all(),DB.prepare('SELECT * FROM profiles WHERE id=?').bind(u.userId).first()]);return json({user:{name:u.fullName||'',email:u.email,broker:u.broker},requests:requests.results,appointments:appointments.results,tickets:tickets.results,profile});
}catch(e){return failure(e)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new Denied(403,'Invalid request origin.');const u=await identity(),{DB,BUCKET}=bindings();
if(req.headers.get('content-type')?.includes('multipart/form-data')){if(Number(req.headers.get('content-length')||0)>11*1024*1024)throw new Denied(413,'Maximum file size is 10 MB.');const form=await req.formData(),id=text(form.get('request'));await own(id,u);const f=form.get('file');if(!(f instanceof File)||!f.size||f.size>10*1024*1024)throw new Denied(400,'Choose a file up to 10 MB.');if(!['image/jpeg','image/png','application/pdf'].includes(f.type))throw new Denied(400,'Choose a JPG, PNG or PDF file.');const bytes=new Uint8Array(await f.arrayBuffer());const valid=f.type==='application/pdf'?new TextDecoder().decode(bytes.slice(0,5))==='%PDF-':f.type==='image/png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)throw new Denied(400,'File contents do not match its type.');if(!BUCKET)throw new Denied(503,'Document storage is unavailable.');const fid=uid();await BUCKET.put(fid,bytes,{httpMetadata:{contentType:f.type}});try{await DB.prepare('INSERT INTO files (id,request,owner,name,mime,bytes,created) VALUES (?,?,?,?,?,?,?)').bind(fid,id,u.userId,text(f.name,180),f.type,f.size,now()).run();}catch(e){await BUCKET.delete(fid);throw e;}await log(u.userId,'Uploaded document',id);return json({id:fid});}
const b=await req.json() as Record<string,unknown>,action=text(b.action),id=text(b.id);
if(action==='submit'){const state=text(b.state)||'Kerala';if(!['Kerala','Tamil Nadu','Karnataka'].includes(state))throw new Denied(400,'Choose Kerala, Tamil Nadu or Karnataka.');const raw=b.details&&typeof b.details==='object'&&!Array.isArray(b.details)?b.details as Record<string,unknown>:{};const details:Record<string,string>={};for(const key of ['district','address','pincode','bedrooms','bathrooms','furnishing','parking','availability','altPhone','contactMethod','language','contactTime'])details[key]=text(raw[key],key==='address'?300:120);details.contactMethod||='Phone';details.language||='English';details.furnishing||='Not specified';for(const [key,choices] of Object.entries({contactMethod:['Phone','Email'],language:['English','Malayalam','Tamil','Kannada','Hindi'],furnishing:['Not specified','Unfurnished','Semi-furnished','Fully furnished']}))if(!choices.includes(details[key]))throw new Denied(400,'Choose a valid '+key+'.');if(details.pincode&&!/^\d{6}$/.test(details.pincode))throw new Denied(400,'Enter a six-digit PIN code.');if(details.altPhone&&!/^\+?[\d\s()-]{7,20}$/.test(details.altPhone))throw new Denied(400,'Enter a valid alternate phone number.');for(const key of ['bedrooms','bathrooms','parking'])if(details[key]&&(!/^\d+$/.test(details[key])||Number(details[key])>100))throw new Denied(400,'Enter a valid '+key+' count.');const mode=text(b.mode),location=text(b.location,200),budget=Number(b.budget),name=text(b.name,100),phone=text(b.phone,30),type=text(b.type,50);if(!modes.includes(mode)||!['Apartment','House','Villa','Land','Commercial'].includes(type)||(!['Sell','Give for Rent'].includes(mode)&&!location)||!Number.isFinite(budget)||budget<=0||budget>1e12||!name||!/^\+?[\d\s()-]{7,20}$/.test(phone)||b.consent!==true)throw new Denied(400,'Complete the required details and accept the privacy consent.');const rid='KB-'+new Date().getFullYear()+'-'+uid().slice(0,8).toUpperCase(),date=now();const map=text(b.map,500);if(map&&!/^https:\/\/(maps\.google\.com|maps\.app\.goo\.gl|www\.google\.com|google\.com|www\.openstreetmap\.org)\//.test(map))throw new Denied(400,'Use a Google Maps or OpenStreetMap location link.');await DB.batch([DB.prepare('INSERT INTO requests (id,owner,mode,type,location,budget,size,notes,name,phone,email,map,status,created,consent,state,details) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(rid,u.userId,mode,type,location,budget,text(b.size,100),text(b.notes,3000),name,phone,u.email,map,'Submitted',date,'Private brokerage consent v1 · '+date,state,JSON.stringify(details)),DB.prepare('INSERT INTO events (id,request,status,note,internal,created) VALUES (?,?,?,?,?,?)').bind(uid(),rid,'Submitted','Your request has reached the brokerage workspace.',0,date)]);await log(u.userId,'Submitted request',rid);return json({id:rid});}
if(action==='profile'){const name=text(b.name,100),phone=text(b.phone,30),contact=text(b.contact,20);if(!name||!['Email','Phone'].includes(contact))throw new Denied(400,'Enter your name and contact preference.');await DB.prepare('INSERT INTO profiles (id,name,phone,contact,consent,created) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,phone=excluded.phone,contact=excluded.contact').bind(u.userId,name,phone,contact,'Private brokerage v1',now()).run();return json({ok:true});}
if(action==='ticket'){if(!text(b.subject)||!text(b.message))throw new Denied(400,'Enter a subject and message.');await DB.prepare('INSERT INTO tickets (id,owner,subject,message,reply,status,created) VALUES (?,?,?,?,?,?,?)').bind(uid(),u.userId,text(b.subject,150),text(b.message,3000),'','Open',now()).run();return json({ok:true});}
if(action==='appointment'){await own(id,u);const date=text(b.date,50),kind=text(b.kind,50);if(!Number.isFinite(Date.parse(date))||Date.parse(date)<=Date.now()||!['Broker consultation','Site visit','Document review'].includes(kind))throw new Denied(400,'Choose a future date and appointment type.');await DB.prepare('INSERT INTO appointments (id,request,owner,date,kind,note,status) VALUES (?,?,?,?,?,?,?)').bind(uid(),id,u.userId,date,kind,text(b.note,1000),'Requested').run();return json({ok:true});}
if(action==='withdraw'){const r=await own(id,u);if(r.owner!==u.userId)throw new Denied(403,'Only the request owner can withdraw.');await DB.batch([DB.prepare("UPDATE requests SET status='Withdrawn' WHERE id=?").bind(id),DB.prepare('INSERT INTO events (id,request,status,note,internal,created) VALUES (?,?,?,?,?,?)').bind(uid(),id,'Withdrawn','Withdrawn by the customer.',0,now())]);return json({ok:true});}
if(!u.broker)throw new Denied(403,'Broker authorisation is required.');
if(action==='status'||action==='note'){await own(id,u);const status=text(b.status),note=text(b.note,3000);if(action==='status'&&!statuses.includes(status))throw new Denied(400,'Choose a valid status.');if(action==='note'&&!note)throw new Denied(400,'Enter a note.');const statements=[DB.prepare('INSERT INTO events (id,request,status,note,internal,created) VALUES (?,?,?,?,?,?)').bind(uid(),id,action==='note'?'Staff note':status,note,action==='note'?1:0,now())];if(action==='status')statements.push(DB.prepare('UPDATE requests SET status=? WHERE id=?').bind(status,id));await DB.batch(statements);}
else if(action==='confirmAppointment'){if(!['Confirmed','Declined','Completed'].includes(text(b.status)))throw new Denied(400,'Invalid appointment status.');await DB.prepare('UPDATE appointments SET status=? WHERE id=?').bind(text(b.status),id).run();}
else if(action==='reply'){if(!text(b.reply))throw new Denied(400,'Enter a reply.');await DB.prepare("UPDATE tickets SET reply=?, status='Replied' WHERE id=?").bind(text(b.reply,3000),id).run();}
else if(action==='commission'){await own(id,u);const value=Number(b.value),rate=Number(b.rate),received=Number(b.received);if(![value,rate,received].every(Number.isFinite)||value<0||rate<0||rate>100||received<0||received>value*rate/100)throw new Denied(400,'Enter valid commission figures.');await DB.prepare('INSERT INTO commissions (request,value,rate,received) VALUES (?,?,?,?) ON CONFLICT(request) DO UPDATE SET value=excluded.value,rate=excluded.rate,received=excluded.received').bind(id,value,rate,received).run();}
else if(action==='match'){const buyer=await own(id,u),seller=await own(text(b.seller),u);if(!((buyer.mode==='Buy'&&seller.mode==='Sell')||(buyer.mode==='Rent'&&seller.mode==='Give for Rent'))||buyer.owner===seller.owner)throw new Denied(400,'Select compatible requests from different customers.');await DB.prepare('INSERT INTO matches (id,buyer,seller,created) VALUES (?,?,?,?)').bind(uid(),id,seller.id,now()).run();}
else throw new Denied(400,'Unknown action.');await log(u.userId,action,id);return json({ok:true});
}catch(e){return failure(e)}}
